[template]
cargo_generate_version = ">=0.10.0"
include = ["*"]

[conditional.'crate_type == "lib"']
ignore = ["src/main.rs", "src/config.rs", ".env", "tests/e2e_tests.rs"]

[placeholders.gh-username]
type = "string"
prompt = "GitHub username (or organization)?"
regex = "^[A-Za-z0-9][A-Za-z0-9-]{0,37}[A-Za-z0-9]$"

[placeholders.protect-main-branch]
type = "bool"
prompt = "Forbid commiting to main branch directly?"
default = false

[placeholders.project-description]
type = "string"
prompt = "Project description?"

[placeholders.nightly]
type = "bool"
prompt = "Nightly channel?"
default = false
