#!/usr/bin/env just --justfile
set dotenv-load := true

list:
    @just --list

help:
    @just list

fmt *FLAGS:
    cargo +nightly fmt  --all {% raw  %}{{FLAGS}}{% endraw %}

check *FLAGS:
    cargo clippy --tests --examples --all-targets --all-features --workspace {% raw  %}{{FLAGS}}{% endraw %}

test *FLAGS:
    cargo nextest run --all-features --workspace {% raw  %}{{FLAGS}}{% endraw %}

{% if crate_type == "bin" %}run *FLAGS:
    cargo run {% raw  %}{{FLAGS}}{% endraw %}{% endif %}

doc *FLAGS:
    cargo doc --no-deps --all-features  --document-private-items --workspace --examples {{FLAGS}}

coverage *FLAGS:
    cargo llvm-cov {% raw %}{{FLAGS}}{% endraw %} --open

benchmark *FLAGS:
    cargo criterion {% raw %}{{FLAGS}}{% endraw %}

thorough-check:
    cargo +nightly udeps --all-targets
    cargo audit
    cargo upgrades

unused-features:
    unused-features analyze
    unused-features build-report --input report.json
    rm report.json
    mv report.html /tmp
    xdg-open /tmp/report.html

pre-commit:
    @just fmt
    @just check -- -D warnings
    @just test
    @just doc
    @just thorough-check
    @just unused-features
    cargo spellcheck fix
    cargo spellcheck reflow

ci:
    @just fmt --check
    @just check -- -D warnings
    @just test
    @just doc
    @just thorough-check
    cargo spellcheck check

init:
    echo # installing git hooks
    pre-commit --version || pip install pre-commit
    pre-commit install || echo "failed to install git hooks!" 1>&2
    echo # installing nightly used by `just fmt` and `cargo udeps`
    rustup install nightly
    echo # installing cargo-binstall for faster setup time
    cargo binstall -V || cargo install cargo-binstall
    echo # things required by `just test`
    cargo binstall cargo-nextest --no-confirm
    {% if crate_type == "bin" %}echo # things required by `just watch`
    cargo binstall cargo-watch --no-confirm{% endif %}
    echo # things required by `just pre-commit`
    cargo binstall cargo-spellcheck --no-confirm
    echo # things required by `just coverage`
    rustup component add llvm-tools-preview
    cargo binstall cargo-llvm-cov --no-confirm
    echo # things required by `just benchmark`
    cargo binstall cargo-criterion --no-confirm
    echo # things required by `just thorough-check`
    cargo binstall cargo-udeps --no-confirm
    cargo binstall cargo-audit --no-confirm
    cargo binstall cargo-upgrades --no-confirm
    cargo binstall cargo-unused-features --no-confirm
